//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mac_Middle_School_Portal.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string mem {
            get {
                return ((string)(this["mem"]));
            }
            set {
                this["mem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string lastProgram {
            get {
                return ((string)(this["lastProgram"]));
            }
            set {
                this["lastProgram"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string theme {
            get {
                return ((string)(this["theme"]));
            }
            set {
                this["theme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string colorScheme {
            get {
                return ((string)(this["colorScheme"]));
            }
            set {
                this["colorScheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool classroomVisible {
            get {
                return ((bool)(this["classroomVisible"]));
            }
            set {
                this["classroomVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 19")]
        public global::System.Drawing.Point classroomLoc {
            get {
                return ((global::System.Drawing.Point)(this["classroomLoc"]));
            }
            set {
                this["classroomLoc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("504, 368")]
        public global::System.Drawing.Point classroomLocation {
            get {
                return ((global::System.Drawing.Point)(this["classroomLocation"]));
            }
            set {
                this["classroomLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("624, 368")]
        public global::System.Drawing.Point macLocation {
            get {
                return ((global::System.Drawing.Point)(this["macLocation"]));
            }
            set {
                this["macLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("744, 368")]
        public global::System.Drawing.Point skywardLocation {
            get {
                return ((global::System.Drawing.Point)(this["skywardLocation"]));
            }
            set {
                this["skywardLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("864, 368")]
        public global::System.Drawing.Point desmosLocation {
            get {
                return ((global::System.Drawing.Point)(this["desmosLocation"]));
            }
            set {
                this["desmosLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("984, 368")]
        public global::System.Drawing.Point prodigyLocation {
            get {
                return ((global::System.Drawing.Point)(this["prodigyLocation"]));
            }
            set {
                this["prodigyLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1104, 368")]
        public global::System.Drawing.Point pivotLocation {
            get {
                return ((global::System.Drawing.Point)(this["pivotLocation"]));
            }
            set {
                this["pivotLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("504, 488")]
        public global::System.Drawing.Point mindplayLocation {
            get {
                return ((global::System.Drawing.Point)(this["mindplayLocation"]));
            }
            set {
                this["mindplayLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("624, 488")]
        public global::System.Drawing.Point mmsLocation {
            get {
                return ((global::System.Drawing.Point)(this["mmsLocation"]));
            }
            set {
                this["mmsLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("744, 488")]
        public global::System.Drawing.Point lunchmenuLocation {
            get {
                return ((global::System.Drawing.Point)(this["lunchmenuLocation"]));
            }
            set {
                this["lunchmenuLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("864, 488")]
        public global::System.Drawing.Point todoBtn {
            get {
                return ((global::System.Drawing.Point)(this["todoBtn"]));
            }
            set {
                this["todoBtn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("984, 488")]
        public global::System.Drawing.Point docsLocation {
            get {
                return ((global::System.Drawing.Point)(this["docsLocation"]));
            }
            set {
                this["docsLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1104, 488")]
        public global::System.Drawing.Point slidesBtn {
            get {
                return ((global::System.Drawing.Point)(this["slidesBtn"]));
            }
            set {
                this["slidesBtn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool currentTimeVisible {
            get {
                return ((bool)(this["currentTimeVisible"]));
            }
            set {
                this["currentTimeVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string myTheme {
            get {
                return ((string)(this["myTheme"]));
            }
            set {
                this["myTheme"] = value;
            }
        }
    }
}
